### ISSUE TITLE
Обновления не работают

### ISSUE THREAD

**Issue by SlalomJohn** [OleksiyPenkov/oleksiypenkov.github.io#1]
Собственно - при нажатии "Проверить наличие обновлений"
![image](https://user-images.githubusercontent.com/65710644/235672518-63052c0d-4e63-4282-9fb3-5544a970284e.png)
![image](https://user-images.githubusercontent.com/65710644/235672642-1ce23807-0e0a-435c-a5c3-5153737e1551.png)

**Comment by OleksiyPenkov** [comment]
Dll-ки не обновил?
